### ISSUE TITLE
405 Method Not Allowed (error code: 0): 405: Method Not Allowed

### ISSUE THREAD

**Issue by ppfeufer** [ppfeufer/aa-rss-to-discord#22]
### Bug Description

```text
==> discordbot.log <==
Ignoring exception in on_connect
Traceback (most recent call last):
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
await coro(*args, **kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.9/site-packages/discord/bot.py", line 793, in on_connect
await self.register_commands()
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.9/site-packages/discord/bot.py", line 460, in register_commands
await self.http.bulk_upsert_command_permissions(
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.9/site-packages/discord/http.py", line 338, in request
raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed
```

Unfortunately, that is all it says. I could nail it down to this app, so it's something from the RSS cog.

**Comment by ppfeufer** [comment]
Ok, this is getting confusing. It does seem to be a general error, not related to this app at all ...

I'll keep this open for a while though ...

**Comment by ppfeufer** [comment]
Yep, that's not related to this app. The error occurs also on systems where this app is not installed.
